```{r}
library(dplyr)
library(readxl)
library(ggplot2)
library(ggpubr)
library(ggExtra)
library(sf)
library(tmap)
library(tmaptools)

dane<-read_xlsx('dane/Dane_powiaty.xlsx', sheet=1) %>% 
  mutate(X1=round(X1,1),
         X2=round(X2,1),
         X3=round(X3,1),
         X4=round(X4,1),
         X5=round(X5,1),
         X6=round(X6,1),
         X7=round(X7,1),
         X8=round(X8,1),
         Kod = substr(Kod,1,4)) %>%
  rename(JPT_KOD_JE = Kod) #zmieniamy nazwe Kod na JPT_KOD_JE
  
zmienne<-read_xlsx('dane/Dane_powiaty.xlsx', sheet=2)
#zajmujemy sie zmienna X8 - Przeciętne miesięczne wynagrodzenie przypadające na jednego zatrudnionego w Polsce w 2020 r. w przekroju powiatów (zł)

#wczytujemy plik shp
wojewodztwa<-st_read('Wojewodztwa/Wojewodztwa.shp')
powiaty<-st_read('powiaty/Powiaty.shp')

head(powiaty)

#łączymy dane z powiaty po JPT_KOD_JE
powiaty_all<-left_join( powiaty, dane)

#tworzymy kartogram dla zmiennej X8
tm_shape(powiaty_all) +
  tm_polygons(col='X8',
              palette=c('springgreen4', 'palegreen3', 'palegreen2', 'palegreen', 'papayawhip','peachpuff', 'sienna1','sienna3'),
              labels=c('3339-3688', '3689-3795', '3796-3913', '3914-4019', '4020-4166', '4167-4313','4314-4615','4616-8488'), 
              breaks =c(3339,3688,3795,3913, 4019,4166,4313, 4615,8488 ))+
  tm_shape(wojewodztwa)+
  tm_borders(col='black', lwd=2)

#tmap_save(powiaty_X8, 'Wykres_X8.png', height=7)
```

```{r}
#Tworzymy kartogram na zmiennej X8 ale dla powiatu w województwie wielkopolski

dane_wlkp <- dane %>% filter(substr(JPT_KOD_JE,1,2)==30)
powiaty_wlkp<-powiaty[substr(powiaty$JPT_KOD_JE,1,2)==30,]

powiaty_wlkp_all<-left_join(powiaty_wlkp,dane_wlkp)

powiaty_wlkp_X8<-tm_shape(powiaty_wlkp_all) +
  tm_polygons(col='X8', 
              palette=c('springgreen4', 'palegreen3', 'palegreen2', 'palegreen', 'papayawhip',
                        'peachpuff', 'sienna1','sienna3'),
              labels=c('3340-3688', '3689-3795', '3796-3913', '3914-4019', '4020-4166', '4167-4313','4314-4615','4616-5501'), 
              breaks =c(3340,3688,3795,3913, 4019,4166,4313, 4615,5501 ))

powiaty_wlkp_X8

```

```{r}

#zadanie 11 ze zestawu 8 kartogram ze strony internetowej bez wklejania do excela (pobieramy tabele bezposrednio ze strony)

#Zadanie 11. Stwórz kartogram w przekroju województw dla gęstości zaludnienia. Pobierz dane ze strony https://pl.wikipedia.org/wiki/Wojew%C3%B3dztwo.
library("stringr")
library(rvest)
url<-'https://pl.wikipedia.org/wiki/Wojew%C3%B3dztwo'
wojewodztwa<-st_read('Wojewodztwa/Wojewodztwa.shp')
strona <- read_html(url)

tabelka <- html_table(html_node(strona, ".wikitable"), fill = TRUE)
wojewodztwa_nazwa<-tabelka["Województwo"]%>%rename('JPT_NAZWA_'="Województwo")
gestosc<-  as.data.frame(as.numeric(sub(",", ".", c(unlist(tabelka['Gęstość zaludnienia[osób/km²]'])), fixed = TRUE)))
gestosc<-gestosc%>%rename("Gestosc_zaludnienia"="as.numeric(sub(\",\", \".\", c(unlist(tabelka[\"Gęstość zaludnienia[osób/km²]\"])), fixed = TRUE))")
woj_all<-left_join( wojewodztwa, data.frame(wojewodztwa_nazwa, gestosc))
print(c(min(gestosc),max(gestosc)))
woj_kart<-tm_shape(woj_all) +
  tm_polygons(col='Gestosc_zaludnienia', breaks=seq(50,380,55))+
  tm_layout(legend.outside=TRUE)+
  tm_text(text='JPT_NAZWA_', size = 0.45)+
  tm_shape(woj_all)+
  tm_text(text='Gestosc_zaludnienia', size = 0.4, ymod=-0.6)
woj_kart

tmap_save(woj_kart, 'Wykres.png', height=7)
```


